### ISSUE TITLE
How to alter default style of <input type="radio"> into a collection of button-like radio?

### ISSUE THREAD

**Issue by billychen0894** [billychen0894/blog#2]
The default style of <input type"radio"> button is a small rounded circle with its adjacent label (if defined). But how do you create a collection of buttons that you can select from, like you submit a rating form on the Internet, based on the default style of radio buttons? 

**Follow the below steps, you can create something like this - [Interactive rating component](https://github.com/billychen0894/frontend-mentor-challenges/tree/main/challenges/Interactive-rating-component).**

1. Set `radio` as fixed position, so each radio button will overlap with its `label`
2. Make each radio button as smallest as possible by setting width size 0
3. Make `radio` invisible with opacity 0%

```css
input[type='radio'] {
  opacity: 0;
  position: fixed;
  width: 0;
}
```

When `radio` is hovered over, the CSS rule applies to its adjacent sibling `label`

```css
input[type='radio']:hover + label {
  background-color: hsl(216, 12%, 54%);
  color: white;
}
```

When `radio` is checked off, the CSS rule applies to its adjacent sibling `label`

```css
input[type='radio']:checked + label {
  background-color: hsl(25, 97%, 53%);
  color: white;
}
```

<img src="https://github.com/billychen0894/frontend-mentor-challenges/blob/main/challenges/Interactive-rating-component/images/screenshot3.png?raw=true" width="250">
